import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  site: 'https://thelaycounseloracademy.com',
  i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
    routing: {
      prefixDefaultLocale: false,
      fallbackType: 'redirect',
    },
    fallback: {
      es: 'en',
    },
  },
  integrations: [
    sitemap({
      /* Spanish fallback stubs (noindex meta-refresh redirects) generated by
       * Astro's i18n fallback for routes that have no Spanish translation
       * should not appear in the sitemap — they are not canonical pages. */
      filter: (page) =>
        !page.match(/\/es\/teachers\//) &&
        !page.match(/\/es\/accessibility\//) &&
        !page.match(/\/es\/thanks\//) &&
        !page.match(/\/thanks\//) &&
        !page.match(/\/404\//) &&
        !page.match(/\/es\/404\//),
      /* Tune priority and changefreq per route. Marketing pages with active
       * content (home, curriculum, pricing) update more often and are higher
       * priority than fixed reference pages (accessibility, teacher bios). */
      serialize(item) {
        /* lastmod = build time: the site redeploys as one static snapshot,
         * so the deploy date is the honest last-modified for every page. */
        item.lastmod = new Date().toISOString();
        const url = item.url.replace(/^https:\/\/thelaycounseloracademy\.com/, "");
        if (url === "/" || url === "/es/") {
          item.changefreq = "weekly";
          item.priority = 1.0;
        } else if (url.match(/\/(curriculum|pricing|faq)\/?$/)) {
          item.changefreq = "monthly";
          item.priority = 0.9;
        } else if (url.match(/^\/es\/(curriculum|pricing|faq)\/?$/)) {
          item.changefreq = "monthly";
          item.priority = 0.9;
        } else if (url.match(/\/(reviews|contact)\/?$/) || url.match(/^\/es\/(reviews|contact)\/?$/)) {
          item.changefreq = "monthly";
          item.priority = 0.7;
        } else if (url.match(/\/teachers\//)) {
          item.changefreq = "yearly";
          item.priority = 0.6;
        } else if (url.match(/\/accessibility\//)) {
          item.changefreq = "yearly";
          item.priority = 0.3;
        }
        return item;
      },
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
  build: {
    /* 'always' inlines all CSS into the HTML — eliminates the two
     * render-blocking stylesheet requests (~600ms on throttled mobile).
     * Page CSS is ~40-80KB raw but compresses to ~10-15KB over the wire. */
    inlineStylesheets: 'always',
  },
  prefetch: {
    prefetchAll: false,
    defaultStrategy: 'hover',
  },
});
